language: node_js
node_js:
- 6.2.2
deploy:
  provider: npm
  email: fraxedas@gmail.com
  api_key:
    secure: BLohbWAh2174uQlsa8rvodbhHP27lNPo4WC/rgwvoXxvuzjWR++a3PtvuPhKEfb3hiGe7QXfnxt50HPH5WVqvnz4cfj7FXzWC9N+UwQ/IVa60bdBxgYv1H3orWQeb6Xp4zExgxSE+ShLm8anPdjuLyNuonG448YyX+43BrGLoM3S5QMWYkvFPgUbUZf/prrklsuHpSMVI1BhtI0zFYkEiO6iHmDRUCf5aG9KPU/SKtdQy5FhWLzlZZc2wQLpvV/0gINeExUZXkL26Jrnl8nN17l3elsk5O88+dojnvvO/7lt540nhDC8wIKoeklYw5kEdsV7/yll0jRBJwnLZKZZ9bmKnimu1zM7Ed1vsK/MEaaGv7z8OFE2vrsKNLOSS9mPj+vBhaiewOUy8JCn080Mls5QSHpe/ePtM/ReBEoc4OpLh0zg8ak0N3lmTYbTnTWEkFl6mTCBNjWk99H/X2WrpUB60YK5c099le9mQtWYvQnp0dfo1oRC1tdFe4hwGZcX+6gx49HJsgP1HCzCujyeCichVM19bJ9yWyK/2f1gBiMwCa/NDRS61bX/brZ/taz9FT//lHC7MqvZgVzREnWmmyNOJKQyhn5VXB23xQdS8Hcr2mvmZi0NiZpo4ZXK/LAzVm8WqUwfwSKU681VvemAJjcKpl67nIMdTnDhgA/1r+k=
  on:
    repo: fraxedas/eloqua-cli
before_install:
- npm install istanbul -g
- npm install mocha-cli -g
- npm install grunt-cli -g
script: mocha
after_script: npm run-script publish-cover
